stages:
  - build
  - deploy

build website:
  image: node
  stage: build
  script:
    - npm install
    - npm run build

netlify:
  stage: deploy
  image: node
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
       
