stages:
  - build
  - test 

build website:
  stage: build	
  image: node
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

test artifact:
  stage: test
  script:
    - |
      if grep "React" ./public/build/index.html; then
        echo "String 'React' not found in index.html"
      else
        echo "String 'React' not found in index.html"
        exit 1
      fi
    
  artifacts:
    paths: 
      - public/
  