stages:
  - build
  - test 

build website:
  stage: build	
  image: node
  script:
    - npm install
    - npm run build -- --output-path=public/
  artifacts:
    paths:
      - public/

test artifact:
  stage: test
  script:
    - grep "React" ./public/index.html