stages:
  - test
  - build
  - deploy

test website:
  image: node
  stage: test
  script: 
    - npm install
    - npm run test

build website:
  image: node
  stage: build
  script:
    - npm install
    - npm run build

netlify:
  stage: deploy
  image: node
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
       
